// <auto-generated />
using System;
using DataStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataStorage.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20230404075956_firstGood")]
    partial class firstGood
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BierBockBackend.Data.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PossiblePoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("BierBockBackend.Data.ChallengePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.ToTable("ChallengeParts");
                });

            modelBuilder.Entity("BierBockBackend.Data.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altitude")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coordinate");
                });

            modelBuilder.Entity("BierBockBackend.Data.DrinkAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("DrinkActions");
                });

            modelBuilder.Entity("BierBockBackend.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AlcoholByVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BeerStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brands")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrewingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CarbohydratesPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CarbonationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EnergyKcalPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FatPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Fermentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FiberPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GenericName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hops")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IBU")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Malt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutriscoreGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProteinsPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaltPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaturatedFatPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SodiumPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SugarsPer100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Taste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yeast")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BierBockBackend.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FavouriteBeerId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FavouriteBeerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataStorage.HelpRelations.ChallengePartChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<int>("ChallengePartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ChallengePartId");

                    b.ToTable("ChallengePartChallenge");
                });

            modelBuilder.Entity("DataStorage.HelpRelations.ChallengeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("ChallengeUser");
                });

            modelBuilder.Entity("BierBockBackend.Data.ChallengePart", b =>
                {
                    b.HasOne("BierBockBackend.Data.Product", "Beer")
                        .WithMany("ChallengeParts")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Beer");
                });

            modelBuilder.Entity("BierBockBackend.Data.DrinkAction", b =>
                {
                    b.HasOne("BierBockBackend.Data.Coordinate", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BierBockBackend.Data.Product", "Product")
                        .WithMany("DrinkActions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BierBockBackend.Data.User", "User")
                        .WithMany("AllDrinkingActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BierBockBackend.Data.User", b =>
                {
                    b.HasOne("BierBockBackend.Data.Product", "FavouriteBeer")
                        .WithMany("UsersHavingThisAsFavouriteBeer")
                        .HasForeignKey("FavouriteBeerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BierBockBackend.Data.Coordinate", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavouriteBeer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DataStorage.HelpRelations.ChallengePartChallenge", b =>
                {
                    b.HasOne("BierBockBackend.Data.ChallengePart", "ChallengePart")
                        .WithMany("Challenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BierBockBackend.Data.Challenge", "Challenge")
                        .WithMany("PartialChallenges")
                        .HasForeignKey("ChallengePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("ChallengePart");
                });

            modelBuilder.Entity("DataStorage.HelpRelations.ChallengeUser", b =>
                {
                    b.HasOne("BierBockBackend.Data.User", "User")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BierBockBackend.Data.Challenge", "Challenge")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BierBockBackend.Data.Challenge", b =>
                {
                    b.Navigation("PartialChallenges");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BierBockBackend.Data.ChallengePart", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("BierBockBackend.Data.Product", b =>
                {
                    b.Navigation("ChallengeParts");

                    b.Navigation("DrinkActions");

                    b.Navigation("UsersHavingThisAsFavouriteBeer");
                });

            modelBuilder.Entity("BierBockBackend.Data.User", b =>
                {
                    b.Navigation("AllDrinkingActions");

                    b.Navigation("UserChallenges");
                });
#pragma warning restore 612, 618
        }
    }
}
